export const green = (text: string) => `\x1b[32m${text}\x1b[39m`;
export const yellow = (text: string) => `\x1b[33m${text}\x1b[39m`;
export const blackOnGreen = (text: string) => `\x1b[30m\x1b[42m${text}\x1b[0m`;
export const red = (text: string) => `\x1b[31m${text}\x1b[39m`;
export const whiteOnRed = (text: string) => `\x1b[37m\x1b[41m${text}\x1b[0m`;
export const bold = (text: string) => `\x1b[1m${text}\x1b[22m`;
export const blue = (text: string) => `\x1b[34m${text}\x1b[39m`;
export const dim = (text: string) => `\x1b[2m${text}\x1b[22m`;
export const blackOnGray = (text: string) => `\x1b[30m\x1b[100m${text}\x1b[0m`;
