import { schema } from '../../../../../index'

describe('Validator Array Method', () => {
  const regexEmail = /^[a-zA-Z0-9._-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/

  it('Should be able to validate the array method and return true if array is valid', () => {
    const stringArray = schema().array().string().validate(['string'])
    const stringArrayMin = schema().array({ min: 1 }).string().validate(['string'])
    const stringArrayMax = schema().array({ max: 3 }).string().validate(['string', 'string', 'string'])
    const emailArray = schema().array().string().email().validate(['any_email@email.com'])
    const UUIDArray = schema().array().string().UUID().validate(['550e8400-e29b-41d4-a716-446655440000'])
    const maxLengthArray = schema().array().string().maxLength(5).validate(['12345'])
    const minLengthArray = schema().array().string().minLength(5).validate(['12345'])
    const timeHHMMArray = schema().array().string().time('HH:MM').validate(['01:01'])
    const minWordArray = schema().array().string().minWord(2).validate(['one two'])
    const regexArray = schema().array().string().regex(regexEmail).validate(['any_email@email.com'])
    const numberArray = schema().array().number().validate([1])
    const floatArray = schema().array().number().float().validate([1.5])
    const integerArray = schema().array().number().integer().validate([2])
    const numberMinArray = schema().array().number().min(1).validate([1])
    const numberMaxArray = schema().array().number().max(2).validate([1])
    const positiveArray = schema().array().number().positive().validate([1])
    const negativeArray = schema().array().number().negative().validate([-1])
    const bigIntArray = schema().array().bigInt().validate([1n])
    const bigIntMinArray = schema().array().bigInt().min(1n).validate([1n])
    const bigIntMaxArray = schema().array().bigInt().max(2n).validate([1n])
    const bigIntPositiveArray = schema().array().bigInt().positive().validate([1n])
    const bigIntNegativeArray = schema().array().bigInt().negative().validate([-1n])
    const booleanArray = schema().array().boolean().validate([true])
    const bufferArray = schema().array().buffer().validate([Buffer.from('test')])
    const functionArray = schema().array().function().validate([() => {}])
    const objectArray = schema().array().object({ key: schema().string() }).validate([{ key: 'string' }])
    const defaultDateArray = schema().array().date().validate([new Date()])
    const dateArray = schema().array().date('ISO8601').validate([new Date()])
    const minDateArray = schema().array().date().min(new Date('2000/01/01')).validate([new Date('2000/01/01')])
    const maxDateArray = schema().array().date().max(new Date('2000/01/01')).validate([new Date('2000/01/01')])
    const oneOfArray = schema().array().oneOf([schema().string(), true]).validate([true])
    const notOneOfArray = schema().array().notOneOf([schema().string(), true]).validate([1])
    const nullableArray = schema().array().string().nullable().validate(null)
    const notRequiredArray = schema().array().string().notRequired().validate(undefined)

    expect(stringArray).toBeTruthy()
    expect(stringArrayMin).toBeTruthy()
    expect(stringArrayMax).toBeTruthy()
    expect(emailArray).toBeTruthy()
    expect(UUIDArray).toBeTruthy()
    expect(maxLengthArray).toBeTruthy()
    expect(minLengthArray).toBeTruthy()
    expect(minWordArray).toBeTruthy()
    expect(timeHHMMArray).toBeTruthy()
    expect(regexArray).toBeTruthy()
    expect(numberArray).toBeTruthy()
    expect(floatArray).toBeTruthy()
    expect(integerArray).toBeTruthy()
    expect(numberMinArray).toBeTruthy()
    expect(numberMaxArray).toBeTruthy()
    expect(positiveArray).toBeTruthy()
    expect(negativeArray).toBeTruthy()
    expect(bigIntArray).toBeTruthy()
    expect(bigIntMinArray).toBeTruthy()
    expect(bigIntMaxArray).toBeTruthy()
    expect(bigIntPositiveArray).toBeTruthy()
    expect(bigIntNegativeArray).toBeTruthy()
    expect(booleanArray).toBeTruthy()
    expect(bufferArray).toBeTruthy()
    expect(functionArray).toBeTruthy()
    expect(objectArray).toBeTruthy()
    expect(defaultDateArray).toBeTruthy()
    expect(dateArray).toBeTruthy()
    expect(minDateArray).toBeTruthy()
    expect(maxDateArray).toBeTruthy()
    expect(oneOfArray).toBeTruthy()
    expect(notOneOfArray).toBeTruthy()
    expect(nullableArray).toBeTruthy()
    expect(notRequiredArray).toBeTruthy()
  })

  it('Should be able to validate the array method and return false if array is invalid', () => {
    const stringArrayMin = schema().array({ min: 2 }).string().validate(['string'])
    const stringArrayMax = schema().array({ max: 2 }).string().validate(['string', 'string', 'string'])
    const notIsArray = schema().array().string().validate(null)
    const stringArray = schema().array().string().validate([null])
    const emailArray = schema().array().string().email().validate(['any_email@mail'])
    const UUIDArray = schema().array().string().UUID().validate(['invalid_uuid'])
    const maxLengthArray = schema().array().string().maxLength(5).validate(['123456'])
    const minLengthArray = schema().array().string().minLength(5).validate(['1234'])
    const timeHHMMArray = schema().array().string().time('HH:MM').validate(['111:11'])
    const minWordArray = schema().array().string().minWord(2).validate(['one'])
    const regexArray = schema().array().string().regex(regexEmail).validate(['any_email@email'])
    const numberArray = schema().array().number().validate([null])
    const floatArray = schema().array().number().float().validate([1])
    const integerArray = schema().array().number().integer().validate([1.5])
    const numberMinArray = schema().array().number().min(2).validate([1])
    const numberMaxArray = schema().array().number().max(2).validate([3])
    const positiveArray = schema().array().number().positive().validate([-1])
    const negativeArray = schema().array().number().negative().validate([1])
    const bigIntArray = schema().array().bigInt().validate([null])
    const bigIntMinArray = schema().array().bigInt().min(2n).validate([1n])
    const bigIntMaxArray = schema().array().bigInt().max(2n).validate([3n])
    const bigIntPositiveArray = schema().array().bigInt().positive().validate([-1n])
    const bigIntNegativeArray = schema().array().bigInt().negative().validate([1n])
    const booleanArray = schema().array().boolean().validate([null])
    const bufferArray = schema().array().buffer().validate([null])
    const functionArray = schema().array().function().validate([null])
    const objectArray = schema().array().object({ key: schema().string() }).validate([null])
    const dateArray = schema().array().date().validate([null])
    const oneOfArray = schema().array().oneOf([schema().string(), true]).validate([1])
    const notOneOfArray = schema().array().notOneOf([schema().string(), true]).validate([true])
    const minDateArray = schema().array().date().min(new Date()).validate([null])
    const maxDateArray = schema().array().date().max(new Date()).validate([null])

    expect(stringArrayMin).toBeFalsy()
    expect(stringArrayMax).toBeFalsy()
    expect(notIsArray).toBeFalsy()
    expect(stringArray).toBeFalsy()
    expect(emailArray).toBeFalsy()
    expect(UUIDArray).toBeFalsy()
    expect(maxLengthArray).toBeFalsy()
    expect(minLengthArray).toBeFalsy()
    expect(minWordArray).toBeFalsy()
    expect(timeHHMMArray).toBeFalsy()
    expect(regexArray).toBeFalsy()
    expect(numberArray).toBeFalsy()
    expect(floatArray).toBeFalsy()
    expect(integerArray).toBeFalsy()
    expect(numberMinArray).toBeFalsy()
    expect(numberMaxArray).toBeFalsy()
    expect(positiveArray).toBeFalsy()
    expect(negativeArray).toBeFalsy()
    expect(bigIntArray).toBeFalsy()
    expect(bigIntMinArray).toBeFalsy()
    expect(bigIntMaxArray).toBeFalsy()
    expect(bigIntPositiveArray).toBeFalsy()
    expect(bigIntNegativeArray).toBeFalsy()
    expect(booleanArray).toBeFalsy()
    expect(bufferArray).toBeFalsy()
    expect(functionArray).toBeFalsy()
    expect(objectArray).toBeFalsy()
    expect(dateArray).toBeFalsy()
    expect(oneOfArray).toBeFalsy()
    expect(notOneOfArray).toBeFalsy()
    expect(minDateArray).toBeFalsy()
    expect(maxDateArray).toBeFalsy()
  })
})
