name: Tests VkrunJS

'on':
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set Timezone to Brasilia, Brazil
      run: sudo ln -fs /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime && sudo dpkg-reconfigure --frontend noninteractive tzdata

    - name: Use Node.js 18.18.0
      uses: actions/setup-node@v2
      with:
        node-version: '18.18.0'

    - name: Install dependencies
      env:
        PORT: 443
      run: yarn install

    - name: Run tests
      run: yarn test

